### ISSUE TITLE
Variable Shadowing Restriction

### ISSUE THREAD

**Issue by JasonGhent** [virtru/lint-trap#22]
http://eslint.org/docs/rules/no-shadow.html

**Comment by nzack** [comment]
I believe the proposal is to update the rule to include a list of 'known' variable names that are allowed to shadow the parent block scope.  These would include common node idioms such as `err`, `next`, `resolve`, `reject`, and `cb`

**Comment by JasonGhent** [comment]
@virtru/employees RFC

**Comment by jwvirtru** [comment]
I can see it being a little bit awkward knowing that some names are whitelisted and not others and having to go look it up or just run the linter, but it's not a major concern on my part.

I'd be interested to know how often people have been burned by variable shadowing. If it's a very rare occurrence, maybe we could consider making it a warning instead of an error to prevent something that rarely happens from affecting the decision behind the name of every variable.

**Comment by nzack** [comment]
The intent of the rule is to make sure someone isn't redefining variables with a different usage in an inner block that has a different purpose or usage.  This hampers readability and doing so is generally code smell.  The issue is that JavaScript extensively uses callbacks that follow a particular pattern, i.e. node-style callbacks, promises, or express style middlewares.  If there is an established pattern I think we should continue to use it, there's few enough of them that I don't think it's too much of an issue.  Can anyone think of any other patterns?

If not, then a small list of 5 is certainly managable as exceptions, imo. and if we need `resolve` and `reject` as exceptions, promises are probably being used incorrectly... maybe we remove those and only have 3.  My guess is that those exceptions will eliminate 90% of the errors we're getting for this.

**Comment by jwvirtru** [comment]
`req` and `res` are used heavily and are very common Node/Express names. Here are some quick counts from the repos I have cloned:

```bash
jwhittle@mbp::src$ ack --js -w req | wc -l
    3452
jwhittle@mbp::src$ ack --js -w res | wc -l
    2297
jwhittle@mbp::src$ ack --js -w cb | wc -l
     591
jwhittle@mbp::src$ ack --js -w next | wc -l
    1117
jwhittle@mbp::src$ ack --js -w err | wc -l
    4013
```

Cloned repos:

```bash
drwxr-xr-x  13 jwhittle  staff    442 Dec  3 14:50 R-3PO
drwxr-xr-x  22 jwhittle  staff    748 Jan 17 10:42 accounts
drwxr-xr-x  22 jwhittle  staff    748 Jan 15 14:40 accounts-service
drwxr-xr-x  17 jwhittle  staff    578 Nov 25 15:58 acm
drwxr-xr-x  13 jwhittle  staff    442 Jan 29 23:32 acm-api
drwxr-xr-x  12 jwhittle  staff    408 Nov 25 16:41 acm-common-utils
drwxr-xr-x  17 jwhittle  staff    578 Nov 17 14:45 admin-panel
drwxr-xr-x  12 jwhittle  staff    408 Jan 28 13:01 analytics-service
drwxr-xr-x  17 jwhittle  staff    578 Jan 20 11:02 automated-test-scripts
drwxr-xr-x  12 jwhittle  staff    408 Jan  5 14:57 binary.js
drwxr-xr-x  33 jwhittle  staff   1122 Feb  2 15:26 browser-extension
drwxr-xr-x  15 jwhittle  staff    510 Nov 19 09:21 checkout-fmw
drwxr-xr-x  12 jwhittle  staff    408 Dec  4 16:07 client-common-utils
drwxr-xr-x  14 jwhittle  staff    476 Dec 30 21:01 dashboard
drwxr-xr-x  12 jwhittle  staff    408 Dec  2 16:18 data-models
drwxr-xr-x  17 jwhittle  staff    578 Jan 15 16:27 db-schemas
drwxr-xr-x  15 jwhittle  staff    510 Nov 17 17:58 deploy-scripts
drwxr-xr-x   8 jwhittle  staff    272 Jan 15 16:27 dlp-schema
drwxr-xr-x  15 jwhittle  staff    510 Dec  2 16:18 domain-worker
drwxr-xr-x  13 jwhittle  staff    442 Jan 29 16:20 drive-extension
drwxr-xr-x  13 jwhittle  staff    442 Feb  2 15:14 drive-extension-fork
drwxr-xr-x   8 jwhittle  staff    272 Jan 27 11:50 lint-trap
drwxr-xr-x  12 jwhittle  staff    408 Jan 26 18:21 pr-prefiller
drwxr-xr-x  18 jwhittle  staff    612 Feb  2 11:13 secure-lib.js
drwxr-xr-x  14 jwhittle  staff    476 Feb  2 13:18 secure-reader
drwxr-xr-x  16 jwhittle  staff    544 Jan  5 14:57 tdf.js
drwxr-xr-x  11 jwhittle  staff    374 Dec  2 11:15 virtru-client-oauth
drwxr-xr-x   6 jwhittle  staff    204 Feb  1 15:01 www-cfg
```

**Comment by Akkuma** [comment]
So late to the game here, but variable shadowing is sort of annoying. I understand the purpose of it, but most of the time you know what you're doing, so wind up with slightly different, potentially more awkward names. However, it doesn't happen that often to me, so I can easily deal with it to prevent shadowing.

**Comment by jwvirtru** [comment]
@Akkuma, I've had to come up with some awkward names to get around the shadowing restriction also, which doesn't help the readability of the code.

Thankfully with ES6 we can do `let` to create a new variable with the same name but with different scope, so this linting rule is no longer an issue for server-side code. It still is with client-side code, but I'm hoping we can start using Babel and write ES6 across the board.

**Comment by Akkuma** [comment]
I'm going to close, since we updated shadowing and ES6 migration will alleviate a lot of this
