### ISSUE TITLE
comma-dangle

### ISSUE THREAD

**Issue by jwvirtru** [virtru/lint-trap#23]
![](http://vignette2.wikia.nocookie.net/reno911/images/7/75/Dangle.jpg/revision/latest?cb=20090314230151)

http://eslint.org/docs/rules/comma-dangle.html

Currently set to `off` for [backend](https://github.com/virtru/lint-trap/blob/master/lib/ci/backend.js#L4) and `error` for [frontend](https://github.com/virtru/lint-trap/blob/master/lib/ci/frontend.js#L4).

### Proposed
Set to `off` for frontend as well. From what I know we don't support IE < 9 anywhere ([SR ref](https://github.com/virtru/secure-reader/blob/master/src/templates/unsupported-browser.swig#L46)), and IE <= 8 is the impetus for this rule.

#### Pros
- Fewer errors caused by reordoring and appending object/array items
- Diffs become cleaner (no change just to add a comma to the previous last item)
- Catharsis. Having purposely dangled commas in both frontend and backend code on previous projects, it really does feel nice not to have to think about comma/no-comma depending on where in an object/array you are just because of legacy browsers.

#### Cons
- There may be some editors that will highlight dangles as errors
- It's conceivable that someone would carry the dangling habit over into JSON files

@virtru/employees RFC

**Comment by nzack** [comment]
Personally, I think the trailing comma is just sloppy... don't feel too terribly strongly about it though.  my ide complains about it too, so that's annoying... but the ide reads the eslint config, so that would go away if we changed it.  Just for the love of God no leading comma, cause fuck that, and if anyone suggests it you deserve to be beaten and left in a ditch.

pros:
-- syntax error, so caught early.
-- one line... easy to see the change
-- i hear ya

cons:
-- ide reads the config
-- syntax error, caught early as well

so ya, i don't feel strongly..

**Comment by JasonGhent** [comment]
I don't mind the trailing comma. I don't like it, but I don't mind it.

**Comment by biscoe916** [comment]
I hate the trailing comma. It must go! As an aside, Google's closure
compiler does *not* allow it.

**Comment by jwvirtru** [comment]
I see I'm in the minority here. I'm a little surprised since in other languages where dangles are allowed I see them used fairly regularly, but oh well looks like our rules will allow me to dangle server side to my heart's content.
